//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasicSetting
    {
        public int ID { get; set; }
        public int TypeOfBasicSettings { get; set; }
        public bool BoolValue { get; set; }
        public int IntValue { get; set; }
        public string Value { get; set; }
        public int Deleted { get; set; }
        public bool Active { get; set; }
        public bool Default { get; set; }
    }
}
