//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailedInvoice
    {
        public int IDInvoice { get; set; }
        public int IDFood { get; set; }
        public Nullable<double> IntoMoney { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual Invoice Invoice { get; set; }
    }
}
