//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityProfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EntityProfile()
        {
            this.EntityProfileItems = new HashSet<EntityProfileItem>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Entity { get; set; }
        public string OriginalType { get; set; }
        public int Deleted { get; set; }
        public bool Active { get; set; }
        public bool Default { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntityProfileItem> EntityProfileItems { get; set; }
    }
}
